/**
 * Serialize schema graph → Prisma schema.
 */

import type { SchemaColumn, SchemaTableData } from "@/types/schema";
import type { SchemaEdge, SchemaNode } from "@/store/schema.store";

function prismaType(col: SchemaColumn): string {
  const t = col.type.toLowerCase();
  if (t === "uuid" || t === "objectid") return "String @db.ObjectId";
  if (t === "text" || t === "string") return "String";
  if (t === "int" || t === "integer") return "Int";
  if (t === "bigint") return "BigInt";
  if (t === "bool" || t === "boolean") return "Boolean";
  if (t === "float" || t === "double") return "Float";
  if (t === "timestamptz" || t === "timestamp") return "DateTime";
  if (t === "json" || t === "jsonb" || t === "object") return "Json";
  if (t === "array") return "Json";
  return "String";
}

function modelName(table: string): string {
  const parts = table.split(/[_-]/).filter(Boolean);
  const base = parts.map((p) => p.charAt(0).toUpperCase() + p.slice(1)).join("");
  return base || "Model";
}

export function schemaToPrisma(nodes: SchemaNode[], edges: SchemaEdge[], provider = "postgresql"): string {
  const lines: string[] = [
    "// Generated by Archly Schema",
    `// ${new Date().toISOString()}`,
    "",
    "generator client {",
    "  provider = \"prisma-client-js\"",
    "}",
    "",
    "datasource db {",
    `  provider = "${provider === "mongodb" ? "mongodb" : provider === "mysql" ? "mysql" : "postgresql"}"`,
    "  url      = env(\"DATABASE_URL\")",
    "}",
    "",
  ];

  const fkEdges = new Map<string, { parent: string; childCol: string }>();
  for (const e of edges) {
    const child = nodes.find((n) => n.id === e.target);
    const parent = nodes.find((n) => n.id === e.source);
    if (!child || !parent) continue;
    const fkCol = e.data?.fkColumn as string | undefined;
    if (fkCol) {
      fkEdges.set(`${child.data?.tableName}:${fkCol}`, {
        parent: String(parent.data?.tableName),
        childCol: fkCol,
      });
    }
  }

  for (const n of nodes) {
    const data = n.data as SchemaTableData;
    if (!data?.tableName) continue;
    const model = modelName(data.tableName);
    lines.push(`model ${model} {`);

    for (const c of data.columns ?? []) {
      const mods: string[] = [];
      if (c.pk) mods.push("@id");
      if (c.unique) mods.push("@unique");
      if (c.nullable === false && !c.pk) mods.push("");

      const fkKey = `${data.tableName}:${c.name}`;
      const fk = c.fk ?? fkEdges.get(fkKey);
      let field = `  ${c.name} ${prismaType(c)}`;
      if (c.pk && provider === "mongodb") field = `  ${c.name} String @id @default(auto()) @map(\"_id\") @db.ObjectId`;
      else if (c.pk) field = `  ${c.name} ${prismaType(c)} @id`;
      else field = `  ${c.name} ${prismaType(c)}${c.nullable === false ? "" : "?"}`;

      lines.push(field);

      if (fk && "table" in fk && fk.table) {
        const rel = modelName(fk.table);
        lines.push(`  ${rel.charAt(0).toLowerCase() + rel.slice(1)} ${rel}? @relation(fields: [${c.name}], references: [${fk.column || "id"}])`);
      } else if (fk && "parent" in fk && fk.parent) {
        const rel = modelName(fk.parent);
        lines.push(`  ${rel.charAt(0).toLowerCase() + rel.slice(1)} ${rel}? @relation(fields: [${c.name}], references: [id])`);
      }
    }

    lines.push(`  @@map(\"${data.tableName}\")`);
    lines.push(`}`);
    lines.push("");
  }

  return lines.join("\n");
}
