/**
 * Serialize schema graph → Mermaid erDiagram + SQL DDL.
 */

import type { SchemaCardinality, SchemaColumn, SchemaTableData } from "@/types/schema";
import type { SchemaEdge, SchemaNode } from "@/store/schema.store";

const CARD_TO_OP: Record<SchemaCardinality, string> = {
  "1:1": "||--||",
  "1:N": "||--o{",
  "N:1": "}o--||",
  "N:M": "}o--o{",
};

function colLine(c: SchemaColumn): string {
  const flags: string[] = [];
  if (c.pk) flags.push("PK");
  if (c.fk) flags.push("FK");
  if (c.unique) flags.push("UK");
  return `    ${c.type} ${c.name}${flags.length ? " " + flags.join(" ") : ""}`;
}

export function schemaToMermaid(nodes: SchemaNode[], edges: SchemaEdge[]): string {
  const lines = ["erDiagram"];

  for (const e of edges) {
    const src = (nodes.find((n) => n.id === e.source)?.data as SchemaTableData | undefined)
      ?.tableName;
    const tgt = (nodes.find((n) => n.id === e.target)?.data as SchemaTableData | undefined)
      ?.tableName;
    if (!src || !tgt) continue;
    const card = (e.data?.cardinality as SchemaCardinality) ?? "1:N";
    const op = CARD_TO_OP[card] ?? "||--o{";
    const label = (e.data?.label as string) || (typeof e.label === "string" ? e.label : "relates");
    const clean = String(label).replace(/·.*/, "").replace(/1:N|1:1|N:M|N:1/g, "").trim() || "relates";
    lines.push(`  ${src} ${op} ${tgt} : "${clean}"`);
  }

  for (const n of nodes) {
    const data = n.data as SchemaTableData;
    if (!data?.tableName) continue;
    lines.push(`  ${data.tableName} {`);
    for (const c of data.columns ?? []) {
      lines.push(colLine(c));
    }
    lines.push(`  }`);
  }

  return lines.join("\n") + "\n";
}

function sqlType(t: string): string {
  const x = t.toLowerCase();
  if (x === "uuid") return "UUID";
  if (x === "text" || x === "string") return "TEXT";
  if (x === "int" || x === "integer") return "INTEGER";
  if (x === "bigint") return "BIGINT";
  if (x === "bool" || x === "boolean") return "BOOLEAN";
  if (x === "timestamptz" || x === "timestamp") return "TIMESTAMPTZ";
  if (x === "date") return "DATE";
  if (x === "json" || x === "jsonb") return "JSONB";
  if (x === "float" || x === "double") return "DOUBLE PRECISION";
  if (x === "numeric" || x === "decimal") return "NUMERIC";
  return t.toUpperCase();
}

export function schemaToSql(nodes: SchemaNode[], edges: SchemaEdge[]): string {
  const lines: string[] = [
    "-- Generated by Archly Schema",
    `-- ${new Date().toISOString()}`,
    "",
  ];

  // Tables first
  for (const n of nodes) {
    const data = n.data as SchemaTableData;
    if (!data?.tableName) continue;
    const cols = data.columns ?? [];
    lines.push(`CREATE TABLE ${data.tableName.toLowerCase()} (`);
    const colSql = cols.map((c) => {
      const parts = [`  ${c.name} ${sqlType(c.type)}`];
      if (c.pk) parts.push("PRIMARY KEY");
      else {
        if (c.unique) parts.push("UNIQUE");
        if (c.nullable === false) parts.push("NOT NULL");
      }
      return parts.join(" ");
    });
    lines.push(colSql.join(",\n"));
    lines.push(`);`);
    lines.push("");
  }

  // FKs from column metadata + edges
  for (const n of nodes) {
    const data = n.data as SchemaTableData;
    if (!data?.tableName) continue;
    for (const c of data.columns ?? []) {
      if (!c.fk || c.fk.table === "?") continue;
      const child = data.tableName.toLowerCase();
      const parent = c.fk.table.toLowerCase();
      const refCol = c.fk.column || "id";
      lines.push(
        `ALTER TABLE ${child} ADD CONSTRAINT fk_${child}_${c.name} FOREIGN KEY (${c.name}) REFERENCES ${parent}(${refCol});`
      );
    }
  }

  // Edges without explicit FK columns still documented as comments
  for (const e of edges) {
    const src = (nodes.find((n) => n.id === e.source)?.data as SchemaTableData | undefined)
      ?.tableName;
    const tgt = (nodes.find((n) => n.id === e.target)?.data as SchemaTableData | undefined)
      ?.tableName;
    if (!src || !tgt) continue;
    const card = (e.data?.cardinality as string) ?? "1:N";
    lines.push(`-- relationship ${src} ${card} ${tgt}`);
  }

  lines.push("");
  return lines.join("\n");
}
