/**
 * Serialize schema graph → MongoDB migration script (mongosh-compatible).
 */

import type { SchemaColumn, SchemaTableData } from "@/types/schema";
import type { SchemaEdge, SchemaNode } from "@/store/schema.store";

function mongoBsonType(col: SchemaColumn): string {
  const t = col.type.toLowerCase();
  if (t === "objectid") return "objectId";
  if (t === "text" || t === "string") return "string";
  if (t === "int" || t === "integer") return "int";
  if (t === "bigint") return "long";
  if (t === "bool" || t === "boolean") return "bool";
  if (t === "float" || t === "double") return "double";
  if (t === "timestamptz" || t === "timestamp") return "date";
  if (t === "array") return "array";
  if (t === "object" || t === "json" || t === "jsonb") return "object";
  return "mixed";
}

function validatorForCollection(columns: SchemaColumn[]): string {
  const props: string[] = [];
  const required: string[] = [];

  for (const c of columns) {
    if (c.name === "_id") continue;
    props.push(`      ${c.name}: { bsonType: "${mongoBsonType(c)}" }`);
    if (c.nullable === false && !c.pk) required.push(`"${c.name}"`);
  }

  const req = required.length ? `\n    required: [${required.join(", ")}],` : "";
  return `{
  $jsonSchema: {${req}
    properties: {
      _id: { bsonType: "objectId" },
${props.join(",\n")}
    }
  }
}`;
}

export function schemaToMongoMigrate(nodes: SchemaNode[], edges: SchemaEdge[], dbName = "mydb"): string {
  const lines: string[] = [
    "// Generated by Archly Schema — MongoDB migration script",
    `// ${new Date().toISOString()}`,
    "// Run with: mongosh \"mongodb+srv://...\" --file migrate.js",
    "",
    `const dbName = ${JSON.stringify(dbName)};`,
    "const db = db.getSiblingDB(dbName);",
    "",
  ];

  for (const n of nodes) {
    const data = n.data as SchemaTableData;
    if (!data?.tableName) continue;
    const coll = data.tableName;
    const validator = validatorForCollection(data.columns ?? []);

    lines.push(`// ── ${coll} ──`);
    lines.push(`if (!db.getCollectionNames().includes(${JSON.stringify(coll)})) {`);
    lines.push(`  db.createCollection(${JSON.stringify(coll)}, { validator: ${validator} });`);
    lines.push(`  print("Created collection: ${coll}");`);
    lines.push(`} else {`);
    lines.push(`  db.runCommand({ collMod: ${JSON.stringify(coll)}, validator: ${validator}, validationLevel: "moderate" });`);
    lines.push(`  print("Updated validator: ${coll}");`);
    lines.push(`}`);
    lines.push("");

    for (const c of data.columns ?? []) {
      if (c.pk || c.name === "_id") {
        lines.push(`db.${coll}.createIndex({ _id: 1 }, { name: "pk_id" });`);
        continue;
      }
      if (c.unique) {
        lines.push(`db.${coll}.createIndex({ ${JSON.stringify(c.name)}: 1 }, { unique: true, name: "uk_${c.name}" });`);
      }
      if (c.fk) {
        lines.push(`db.${coll}.createIndex({ ${JSON.stringify(c.name)}: 1 }, { name: "idx_${c.name}_fk" });`);
      }
    }
    lines.push("");
  }

  lines.push("// Relationships (documentation — enforce in application layer):");
  for (const e of edges) {
    const src = (nodes.find((n) => n.id === e.source)?.data as SchemaTableData | undefined)?.tableName;
    const tgt = (nodes.find((n) => n.id === e.target)?.data as SchemaTableData | undefined)?.tableName;
    if (!src || !tgt) continue;
    const fk = e.data?.fkColumn ? ` via ${e.data.fkColumn}` : "";
    lines.push(`// ${src} → ${tgt}${fk} (${e.data?.cardinality ?? "1:N"})`);
  }

  lines.push("");
  return lines.join("\n");
}
