/**
 * Serialize edge decision ledger to ADR markdown.
 */

export function serializeDecisionAdr(
  nodes: { id: string; data?: { label?: string } }[],
  edges: {
    id: string;
    source: string;
    target: string;
    data?: { decisionWhy?: string; requestContract?: string; responseContract?: string };
  }[]
): string {
  const label = (id: string) => nodes.find((n) => n.id === id)?.data?.label ?? id;
  const lines = [
    "# Architecture Decision Record",
    "",
    `_Generated by Archly · ${new Date().toISOString().slice(0, 10)}_`,
    "",
    "## Decisions",
    "",
  ];

  const withWhy = edges.filter((e) => e.data?.decisionWhy?.trim());
  if (!withWhy.length) {
    lines.push("_No edge decisions recorded yet. Add “Why this edge?” in Properties._", "");
  } else {
    for (const e of withWhy) {
      lines.push(`### ${label(e.source)} → ${label(e.target)}`);
      lines.push("");
      lines.push(e.data!.decisionWhy!.trim());
      lines.push("");
    }
  }

  const withContract = edges.filter(
    (e) => e.data?.requestContract?.trim() || e.data?.responseContract?.trim()
  );
  if (withContract.length) {
    lines.push("## Contracts on the wire", "");
    for (const e of withContract) {
      lines.push(`### ${label(e.source)} → ${label(e.target)}`);
      lines.push("");
      if (e.data?.requestContract?.trim()) {
        lines.push("**Request**");
        lines.push("```");
        lines.push(e.data.requestContract.trim());
        lines.push("```");
        lines.push("");
      }
      if (e.data?.responseContract?.trim()) {
        lines.push("**Response**");
        lines.push("```");
        lines.push(e.data.responseContract.trim());
        lines.push("```");
        lines.push("");
      }
    }
  }

  return lines.join("\n");
}

export function downloadText(filename: string, text: string) {
  const blob = new Blob([text], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
